export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const LOGOUT = 'LOGOUT';

export const GET_CAMPGROUNDS = 'GET_CAMPGROUNDS';
export const GET_CAMPGROUND = 'GET_CAMPGROUND';
export const CAMPGROUND_ERROR = 'CAMPGROUND_ERROR';
export const ADD_CAMPGROUND = 'ADD_CAMPGROUND';
export const DELETE_CAMPGROUND = 'DELETE_CAMPGROUND';
export const EDIT_CAMPGROUND = 'EDIT_CAMPGROUND';

export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
